### ISSUE TITLE
there is an error :  'myImage.ocr()'

### ISSUE THREAD

**Issue by MakeToast** [BiometricVox/zAI#1]
originalText = myImage.ocr() has an error
when I use backend="Google"

GOOGLE_CLOUD_API_KEY is empty. Using local.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choeyujin/Project/Purdue_Proejct/UAV-Aerial-Mapping-and-Survey/DroneMosaic/zAI/zAI/zimage.py", line 304, in ocr

and local , Microsoft also have same error.
So I found that I have to use zAI.utils.set_backend_key() below,
zAI.utils.set_backend_key(key_name='GOOGLE_CLOUD_API_KEY',key_value='(자신의 API키를 넣는다)',save=True)
If so, what is the key_value?

**Comment by MakeToast** [comment]
Sorry I find the answer.
